#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LaBocana")]
	public partial class DBLaBocanaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCLIENTE(CLIENTE instance);
    partial void UpdateCLIENTE(CLIENTE instance);
    partial void DeleteCLIENTE(CLIENTE instance);
    partial void InsertMENU(MENU instance);
    partial void UpdateMENU(MENU instance);
    partial void DeleteMENU(MENU instance);
    partial void InsertMESA(MESA instance);
    partial void UpdateMESA(MESA instance);
    partial void DeleteMESA(MESA instance);
    partial void InsertORDEN(ORDEN instance);
    partial void UpdateORDEN(ORDEN instance);
    partial void DeleteORDEN(ORDEN instance);
    #endregion
		
		public DBLaBocanaDataContext() : 
				base(global::Datos.Properties.Settings.Default.LaBocanaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBLaBocanaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLaBocanaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLaBocanaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLaBocanaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CLIENTE> CLIENTE
		{
			get
			{
				return this.GetTable<CLIENTE>();
			}
		}
		
		public System.Data.Linq.Table<MENU> MENU
		{
			get
			{
				return this.GetTable<MENU>();
			}
		}
		
		public System.Data.Linq.Table<MESA> MESA
		{
			get
			{
				return this.GetTable<MESA>();
			}
		}
		
		public System.Data.Linq.Table<ORDEN> ORDEN
		{
			get
			{
				return this.GetTable<ORDEN>();
			}
		}
		
		public System.Data.Linq.Table<CAJA> CAJA
		{
			get
			{
				return this.GetTable<CAJA>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarCliente")]
		public ISingleResult<BuscarClienteResult> BuscarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Desde", DbType="Int")] System.Nullable<int> desde, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hasta", DbType="Int")] System.Nullable<int> hasta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Buscar", DbType="VarChar(MAX)")] string buscar)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), desde, hasta, buscar);
			return ((ISingleResult<BuscarClienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EditarCliente")]
		public int EditarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Cliente", DbType="Int")] System.Nullable<int> id_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(MAX)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombres", DbType="VarChar(MAX)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="VarChar(MAX)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(MAX)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(MAX)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Mesa", DbType="Int")] System.Nullable<int> id_Mesa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Cliente, cedula, nombres, apellidos, direccion, telefono, id_Mesa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarCliente")]
		public int EliminarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Cliente", DbType="Int")] System.Nullable<int> id_Cliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Cliente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarCliente")]
		public int InsertarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(MAX)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombres", DbType="VarChar(MAX)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="VarChar(MAX)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(MAX)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(MAX)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Mesa", DbType="Int")] System.Nullable<int> id_Mesa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula, nombres, apellidos, direccion, telefono, id_Mesa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MostrarCliente")]
		public ISingleResult<MostrarClienteResult> MostrarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Desde", DbType="Int")] System.Nullable<int> desde, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hasta", DbType="Int")] System.Nullable<int> hasta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), desde, hasta);
			return ((ISingleResult<MostrarClienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EditarMenu")]
		public int EditarMenu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Menu", DbType="Int")] System.Nullable<int> id_Menu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(MAX)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> precio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Menu, nombre, precio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarMenu")]
		public int EliminarMenu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Menu", DbType="Int")] System.Nullable<int> id_Menu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Menu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarMenu")]
		public int InsertarMenu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(MAX)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(19,2)")] System.Nullable<decimal> precio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, precio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listarMenu")]
		public ISingleResult<listarMenuResult> listarMenu()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<listarMenuResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarCaja")]
		public int InsertarCaja([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SaldoApertura", DbType="Decimal(19,2)")] System.Nullable<decimal> saldoApertura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SaldoCierre", DbType="Decimal(19,2)")] System.Nullable<decimal> saldoCierre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SaldoActual", DbType="Decimal(19,2)")] System.Nullable<decimal> saldoActual, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Observacion", DbType="VarChar(MAX)")] string observacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="DateTime")] System.Nullable<System.DateTime> fecha)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), saldoApertura, saldoCierre, saldoActual, observacion, fecha);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CerrarCaja")]
		public int CerrarCaja([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Caja", DbType="Int")] System.Nullable<int> id_Caja)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Caja);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AnularCaja")]
		public int AnularCaja([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Caja", DbType="Int")] System.Nullable<int> id_Caja)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Caja);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MostrarCaja")]
		public ISingleResult<MostrarCajaResult> MostrarCaja()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MostrarCajaResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLIENTE")]
	public partial class CLIENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Cliente;
		
		private string _Cedula;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private System.Nullable<int> _Id_Mesa;
		
		private EntityRef<MESA> _MESA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_ClienteChanging(int value);
    partial void OnId_ClienteChanged();
    partial void OnCedulaChanging(string value);
    partial void OnCedulaChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnId_MesaChanging(System.Nullable<int> value);
    partial void OnId_MesaChanged();
    #endregion
		
		public CLIENTE()
		{
			this._MESA = default(EntityRef<MESA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Cliente
		{
			get
			{
				return this._Id_Cliente;
			}
			set
			{
				if ((this._Id_Cliente != value))
				{
					this.OnId_ClienteChanging(value);
					this.SendPropertyChanging();
					this._Id_Cliente = value;
					this.SendPropertyChanged("Id_Cliente");
					this.OnId_ClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(MAX)")]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this.OnCedulaChanging(value);
					this.SendPropertyChanging();
					this._Cedula = value;
					this.SendPropertyChanged("Cedula");
					this.OnCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(MAX)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(MAX)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(MAX)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(MAX)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Mesa", DbType="Int")]
		public System.Nullable<int> Id_Mesa
		{
			get
			{
				return this._Id_Mesa;
			}
			set
			{
				if ((this._Id_Mesa != value))
				{
					if (this._MESA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_MesaChanging(value);
					this.SendPropertyChanging();
					this._Id_Mesa = value;
					this.SendPropertyChanged("Id_Mesa");
					this.OnId_MesaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MESA_CLIENTE", Storage="_MESA", ThisKey="Id_Mesa", OtherKey="Id_Mesa", IsForeignKey=true)]
		public MESA MESA
		{
			get
			{
				return this._MESA.Entity;
			}
			set
			{
				MESA previousValue = this._MESA.Entity;
				if (((previousValue != value) 
							|| (this._MESA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MESA.Entity = null;
						previousValue.CLIENTE.Remove(this);
					}
					this._MESA.Entity = value;
					if ((value != null))
					{
						value.CLIENTE.Add(this);
						this._Id_Mesa = value.Id_Mesa;
					}
					else
					{
						this._Id_Mesa = default(Nullable<int>);
					}
					this.SendPropertyChanged("MESA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MENU")]
	public partial class MENU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Menu;
		
		private string _Nombre;
		
		private System.Nullable<decimal> _Precio;
		
		private EntitySet<ORDEN> _ORDEN;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_MenuChanging(int value);
    partial void OnId_MenuChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnPrecioChanging(System.Nullable<decimal> value);
    partial void OnPrecioChanged();
    #endregion
		
		public MENU()
		{
			this._ORDEN = new EntitySet<ORDEN>(new Action<ORDEN>(this.attach_ORDEN), new Action<ORDEN>(this.detach_ORDEN));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Menu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Menu
		{
			get
			{
				return this._Id_Menu;
			}
			set
			{
				if ((this._Id_Menu != value))
				{
					this.OnId_MenuChanging(value);
					this.SendPropertyChanging();
					this._Id_Menu = value;
					this.SendPropertyChanged("Id_Menu");
					this.OnId_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(MAX)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MENU_ORDEN", Storage="_ORDEN", ThisKey="Id_Menu", OtherKey="Id_Menu")]
		public EntitySet<ORDEN> ORDEN
		{
			get
			{
				return this._ORDEN;
			}
			set
			{
				this._ORDEN.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ORDEN(ORDEN entity)
		{
			this.SendPropertyChanging();
			entity.MENU = this;
		}
		
		private void detach_ORDEN(ORDEN entity)
		{
			this.SendPropertyChanging();
			entity.MENU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MESA")]
	public partial class MESA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Mesa;
		
		private string _Estado;
		
		private System.Nullable<int> _Id_Orden;
		
		private EntitySet<CLIENTE> _CLIENTE;
		
		private EntityRef<ORDEN> _ORDEN;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_MesaChanging(int value);
    partial void OnId_MesaChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnId_OrdenChanging(System.Nullable<int> value);
    partial void OnId_OrdenChanged();
    #endregion
		
		public MESA()
		{
			this._CLIENTE = new EntitySet<CLIENTE>(new Action<CLIENTE>(this.attach_CLIENTE), new Action<CLIENTE>(this.detach_CLIENTE));
			this._ORDEN = default(EntityRef<ORDEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Mesa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Mesa
		{
			get
			{
				return this._Id_Mesa;
			}
			set
			{
				if ((this._Id_Mesa != value))
				{
					this.OnId_MesaChanging(value);
					this.SendPropertyChanging();
					this._Id_Mesa = value;
					this.SendPropertyChanged("Id_Mesa");
					this.OnId_MesaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(MAX)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Orden", DbType="Int")]
		public System.Nullable<int> Id_Orden
		{
			get
			{
				return this._Id_Orden;
			}
			set
			{
				if ((this._Id_Orden != value))
				{
					if (this._ORDEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_OrdenChanging(value);
					this.SendPropertyChanging();
					this._Id_Orden = value;
					this.SendPropertyChanged("Id_Orden");
					this.OnId_OrdenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MESA_CLIENTE", Storage="_CLIENTE", ThisKey="Id_Mesa", OtherKey="Id_Mesa")]
		public EntitySet<CLIENTE> CLIENTE
		{
			get
			{
				return this._CLIENTE;
			}
			set
			{
				this._CLIENTE.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ORDEN_MESA", Storage="_ORDEN", ThisKey="Id_Orden", OtherKey="Id_Orden", IsForeignKey=true)]
		public ORDEN ORDEN
		{
			get
			{
				return this._ORDEN.Entity;
			}
			set
			{
				ORDEN previousValue = this._ORDEN.Entity;
				if (((previousValue != value) 
							|| (this._ORDEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ORDEN.Entity = null;
						previousValue.MESA.Remove(this);
					}
					this._ORDEN.Entity = value;
					if ((value != null))
					{
						value.MESA.Add(this);
						this._Id_Orden = value.Id_Orden;
					}
					else
					{
						this._Id_Orden = default(Nullable<int>);
					}
					this.SendPropertyChanged("ORDEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CLIENTE(CLIENTE entity)
		{
			this.SendPropertyChanging();
			entity.MESA = this;
		}
		
		private void detach_CLIENTE(CLIENTE entity)
		{
			this.SendPropertyChanging();
			entity.MESA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ORDEN")]
	public partial class ORDEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Orden;
		
		private System.Nullable<int> _Id_Menu;
		
		private System.Nullable<decimal> _Total;
		
		private string _Sugerencia;
		
		private EntitySet<MESA> _MESA;
		
		private EntityRef<MENU> _MENU;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_OrdenChanging(int value);
    partial void OnId_OrdenChanged();
    partial void OnId_MenuChanging(System.Nullable<int> value);
    partial void OnId_MenuChanged();
    partial void OnTotalChanging(System.Nullable<decimal> value);
    partial void OnTotalChanged();
    partial void OnSugerenciaChanging(string value);
    partial void OnSugerenciaChanged();
    #endregion
		
		public ORDEN()
		{
			this._MESA = new EntitySet<MESA>(new Action<MESA>(this.attach_MESA), new Action<MESA>(this.detach_MESA));
			this._MENU = default(EntityRef<MENU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Orden", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Orden
		{
			get
			{
				return this._Id_Orden;
			}
			set
			{
				if ((this._Id_Orden != value))
				{
					this.OnId_OrdenChanging(value);
					this.SendPropertyChanging();
					this._Id_Orden = value;
					this.SendPropertyChanged("Id_Orden");
					this.OnId_OrdenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Menu", DbType="Int")]
		public System.Nullable<int> Id_Menu
		{
			get
			{
				return this._Id_Menu;
			}
			set
			{
				if ((this._Id_Menu != value))
				{
					if (this._MENU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_MenuChanging(value);
					this.SendPropertyChanging();
					this._Id_Menu = value;
					this.SendPropertyChanged("Id_Menu");
					this.OnId_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sugerencia", DbType="VarChar(MAX)")]
		public string Sugerencia
		{
			get
			{
				return this._Sugerencia;
			}
			set
			{
				if ((this._Sugerencia != value))
				{
					this.OnSugerenciaChanging(value);
					this.SendPropertyChanging();
					this._Sugerencia = value;
					this.SendPropertyChanged("Sugerencia");
					this.OnSugerenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ORDEN_MESA", Storage="_MESA", ThisKey="Id_Orden", OtherKey="Id_Orden")]
		public EntitySet<MESA> MESA
		{
			get
			{
				return this._MESA;
			}
			set
			{
				this._MESA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MENU_ORDEN", Storage="_MENU", ThisKey="Id_Menu", OtherKey="Id_Menu", IsForeignKey=true)]
		public MENU MENU
		{
			get
			{
				return this._MENU.Entity;
			}
			set
			{
				MENU previousValue = this._MENU.Entity;
				if (((previousValue != value) 
							|| (this._MENU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MENU.Entity = null;
						previousValue.ORDEN.Remove(this);
					}
					this._MENU.Entity = value;
					if ((value != null))
					{
						value.ORDEN.Add(this);
						this._Id_Menu = value.Id_Menu;
					}
					else
					{
						this._Id_Menu = default(Nullable<int>);
					}
					this.SendPropertyChanged("MENU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MESA(MESA entity)
		{
			this.SendPropertyChanging();
			entity.ORDEN = this;
		}
		
		private void detach_MESA(MESA entity)
		{
			this.SendPropertyChanging();
			entity.ORDEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CAJA")]
	public partial class CAJA
	{
		
		private int _Id_Caja;
		
		private System.Nullable<decimal> _SaldoApertura;
		
		private System.Nullable<decimal> _SaldoCierre;
		
		private System.Nullable<decimal> _SaldoActual;
		
		private string _Observacion;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		public CAJA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Caja", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id_Caja
		{
			get
			{
				return this._Id_Caja;
			}
			set
			{
				if ((this._Id_Caja != value))
				{
					this._Id_Caja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaldoApertura", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> SaldoApertura
		{
			get
			{
				return this._SaldoApertura;
			}
			set
			{
				if ((this._SaldoApertura != value))
				{
					this._SaldoApertura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaldoCierre", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> SaldoCierre
		{
			get
			{
				return this._SaldoCierre;
			}
			set
			{
				if ((this._SaldoCierre != value))
				{
					this._SaldoCierre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaldoActual", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> SaldoActual
		{
			get
			{
				return this._SaldoActual;
			}
			set
			{
				if ((this._SaldoActual != value))
				{
					this._SaldoActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(MAX)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this._Observacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
	}
	
	public partial class BuscarClienteResult
	{
		
		private int _Id_Cliente;
		
		private string _Cedula;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private string _Direccion;
		
		private System.Nullable<int> _Id_Mesa;
		
		private string _Telefono;
		
		private string _Estado;
		
		public BuscarClienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Cliente", DbType="Int NOT NULL")]
		public int Id_Cliente
		{
			get
			{
				return this._Id_Cliente;
			}
			set
			{
				if ((this._Id_Cliente != value))
				{
					this._Id_Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(MAX)")]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(MAX)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(MAX)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(MAX)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Mesa", DbType="Int")]
		public System.Nullable<int> Id_Mesa
		{
			get
			{
				return this._Id_Mesa;
			}
			set
			{
				if ((this._Id_Mesa != value))
				{
					this._Id_Mesa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(MAX)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(MAX)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class MostrarClienteResult
	{
		
		private int _Id_Cliente;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private string _Direccion;
		
		private System.Nullable<int> _Id_Mesa;
		
		private string _Telefono;
		
		private string _Estado;
		
		public MostrarClienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Cliente", DbType="Int NOT NULL")]
		public int Id_Cliente
		{
			get
			{
				return this._Id_Cliente;
			}
			set
			{
				if ((this._Id_Cliente != value))
				{
					this._Id_Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(MAX)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(MAX)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(MAX)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Mesa", DbType="Int")]
		public System.Nullable<int> Id_Mesa
		{
			get
			{
				return this._Id_Mesa;
			}
			set
			{
				if ((this._Id_Mesa != value))
				{
					this._Id_Mesa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(MAX)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(MAX)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class listarMenuResult
	{
		
		private int _Id_Menu;
		
		private string _Nombre;
		
		private System.Nullable<decimal> _Precio;
		
		public listarMenuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Menu", DbType="Int NOT NULL")]
		public int Id_Menu
		{
			get
			{
				return this._Id_Menu;
			}
			set
			{
				if ((this._Id_Menu != value))
				{
					this._Id_Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(MAX)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
	}
	
	public partial class MostrarCajaResult
	{
		
		private int _Id_Caja;
		
		private System.Nullable<decimal> _SaldoApertura;
		
		private System.Nullable<decimal> _SaldoCierre;
		
		private System.Nullable<decimal> _SaldoActual;
		
		private string _Observacion;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		public MostrarCajaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Caja", DbType="Int NOT NULL")]
		public int Id_Caja
		{
			get
			{
				return this._Id_Caja;
			}
			set
			{
				if ((this._Id_Caja != value))
				{
					this._Id_Caja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaldoApertura", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> SaldoApertura
		{
			get
			{
				return this._SaldoApertura;
			}
			set
			{
				if ((this._SaldoApertura != value))
				{
					this._SaldoApertura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaldoCierre", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> SaldoCierre
		{
			get
			{
				return this._SaldoCierre;
			}
			set
			{
				if ((this._SaldoCierre != value))
				{
					this._SaldoCierre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaldoActual", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> SaldoActual
		{
			get
			{
				return this._SaldoActual;
			}
			set
			{
				if ((this._SaldoActual != value))
				{
					this._SaldoActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(MAX)")]
		public string Observacion
		{
			get
			{
				return this._Observacion;
			}
			set
			{
				if ((this._Observacion != value))
				{
					this._Observacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
