<?xml version="1.0" encoding="utf-8"?><Database Name="LaBocana" Class="DBLaBocanaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ACXELAMBROS3286;Initial Catalog=LaBocana;Integrated Security=True" SettingsObjectName="Datos.Properties.Settings" SettingsPropertyName="LaBocanaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CLIENTE" Member="CLIENTE">
    <Type Name="CLIENTE">
      <Column Name="Id_Cliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cedula" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Id_Mesa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MESA_CLIENTE" Member="MESA" ThisKey="Id_Mesa" OtherKey="Id_Mesa" Type="MESA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MENU" Member="MENU">
    <Type Name="MENU">
      <Column Name="Id_Menu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="MENU_ORDEN" Member="ORDEN" ThisKey="Id_Menu" OtherKey="Id_Menu" Type="ORDEN" />
    </Type>
  </Table>
  <Table Name="dbo.MESA" Member="MESA">
    <Type Name="MESA">
      <Column Name="Id_Mesa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Id_Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MESA_CLIENTE" Member="CLIENTE" ThisKey="Id_Mesa" OtherKey="Id_Mesa" Type="CLIENTE" />
      <Association Name="ORDEN_MESA" Member="ORDEN" ThisKey="Id_Orden" OtherKey="Id_Orden" Type="ORDEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ORDEN" Member="ORDEN">
    <Type Name="ORDEN">
      <Column Name="Id_Orden" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Menu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Sugerencia" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="ORDEN_MESA" Member="MESA" ThisKey="Id_Orden" OtherKey="Id_Orden" Type="MESA" />
      <Association Name="MENU_ORDEN" Member="MENU" ThisKey="Id_Menu" OtherKey="Id_Menu" Type="MENU" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.BuscarCliente" Method="BuscarCliente">
    <Parameter Name="Desde" Parameter="desde" Type="System.Int32" DbType="Int" />
    <Parameter Name="Hasta" Parameter="hasta" Type="System.Int32" DbType="Int" />
    <Parameter Name="Buscar" Parameter="buscar" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="BuscarClienteResult">
      <Column Name="Id_Cliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cedula" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Id_Mesa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.EditarCliente" Method="EditarCliente">
    <Parameter Name="Id_Cliente" Parameter="id_Cliente" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Nombres" Parameter="nombres" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Apellidos" Parameter="apellidos" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Id_Mesa" Parameter="id_Mesa" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EliminarCliente" Method="EliminarCliente">
    <Parameter Name="Id_Cliente" Parameter="id_Cliente" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertarCliente" Method="InsertarCliente">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Nombres" Parameter="nombres" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Apellidos" Parameter="apellidos" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Id_Mesa" Parameter="id_Mesa" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.MostrarCliente" Method="MostrarCliente">
    <Parameter Name="Desde" Parameter="desde" Type="System.Int32" DbType="Int" />
    <Parameter Name="Hasta" Parameter="hasta" Type="System.Int32" DbType="Int" />
    <ElementType Name="MostrarClienteResult">
      <Column Name="Id_Cliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Id_Mesa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.EditarMenu" Method="EditarMenu">
    <Parameter Name="Id_Menu" Parameter="id_Menu" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="precio" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EliminarMenu" Method="EliminarMenu">
    <Parameter Name="Id_Menu" Parameter="id_Menu" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertarMenu" Method="InsertarMenu">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="precio" Type="System.Decimal" DbType="Decimal(19,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.listarMenu" Method="listarMenu">
    <ElementType Name="listarMenuResult">
      <Column Name="Id_Menu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>